SRC_URI += " \
    file://0001-AOM-5521-Add-AOM-5521-project.patch \
    file://0002-AOM-5521-fixed-otg-serial-download-issue.patch \
    file://0003-AOM-5521-Add-SW_RESET_OUT.patch \
    file://0004-ALL-config-Add-ADVANTECH-IMX8-IMX9-definition.patch \
    file://0005-ALL-NET-Add-reading-eth0-and-eth1-MAC-address-from-s.patch \
    file://0006-AOM-5521-config-Enable-eth0-eth1-MAC-address-write-m.patch \
    file://0007-ALL-NET-driver-Add-eth2-eth3-MAC-address-getting-met.patch \
    file://0008-AOM-5521-config-Enable-eth2-MAC-address-write-method.patch \
    file://0009-AOM-5521-SPI-config-Support-WINBOND-SPI-flash-and-mo.patch \
    file://0010-AOM-5521-dts-Support-w25q64-SPI-nor-flash.patch \
    file://0011-AOM-5521-USB-config-Enable-USB-GADGET-options.patch \
    file://0013-AOM-5521-dts-Enable-USB2-gadget-for-UUU-tool.patch \
    file://0014-AOM-5521-USB-driver-Move-USB2_BOOT-handling-from-evk.patch \
    file://0015-Add-common-folder.patch \
"
